# Generated by Django 4.1.4 on 2023-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='imagefolder')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenuName', models.CharField(max_length=20)),
                ('ManagerName', models.CharField(max_length=20)),
                ('ManagerPlace', models.CharField(max_length=20)),
                ('ManagerNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VenueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=20)),
                ('VenuName', models.CharField(default='', max_length=20)),
                ('VenuType', models.CharField(default='', max_length=20)),
                ('VenuOwner', models.CharField(default='', max_length=20)),
                ('VenuNumber', models.IntegerField(default=0)),
                ('VenuDescription', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='imagefolder')),
            ],
        ),
    ]
