# Generated by Django 4.1.4 on 2023-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
