# Generated by Django 4.1.4 on 2023-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_registertable_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktable',
            name='function',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booktable',
            name='starttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
